### ISSUE TITLE
Default Fallback with Lateral Fallback

### ISSUE THREAD

**Issue by Keith-Ball** [HedgehogDevelopment/sitecore-field-fallback#10]
Hello,
I'm seeing two, maybe related, issues with Sitecore 7.2 Update 2.

1. Lateral fallback doesn't work off of a default field value. We're attempting to set the Breadcrumbs to the Navigation Title and have the Navigation Title based off of the $name. Breadcrumbs was not updating properly, but when I modified Navigation Title it updated to the new, non-fallback, value.

2. For the same example, there is an odd bug where the Breadcrumbs are being seen as falling back on the Default Field Processor (Believed to have been modified, saved, then removed) even though it's empty. I was able to modify the pipeline to have Literal appear before default in an attempt to fix this issue, which is how I ran into the first issue.

**Comment by hhog-tkamin** [comment]
Updated the documentation to provide better information on having Lateral Fallback work on nested fallback.
