### ISSUE TITLE
XML error polutes the log

### ISSUE THREAD

**Issue by tdelplace** [HedgehogDevelopment/sitecore-field-fallback#19]
Hello,

I did install the module on a Sitecore 8 update-2 (using the sitecore-8 branch), and configured only the lateral field fallback.

Since then, I have the attached error poluting my log.  When editing / saving a lot of items, I can come to gigabytes of log...

The error comes from the fact that the content of my field is not xml, and that in the Initialize method of the FieldFallback.Processors.Data.Items.FallbackItem class, you try to parse it as xml.

Here attached, the log entry that occurs hundreds of time:
[Issue-xml.txt](https://github.com/HedgehogDevelopment/sitecore-field-fallback/files/49542/Issue-xml.txt)

Thomas

**Comment by seankearney** [comment]
We see the problem. Sitecore is throwing an exception for the value you have in that field. We can work around that.

**Comment by hhog-tkamin** [comment]
pull request was accepted that included fix for this issue
