### ISSUE TITLE
Allow fallback for media items

### ISSUE THREAD

**Issue by Refactored** [HedgehogDevelopment/sitecore-field-fallback#4]
Currently Field Fallback only supports content items but we ran into a need to also have this work at the media item level (specifically to pull "Title" from a linked to asset).

Details in this Twitter conversation: https://twitter.com/kyleheon/status/431500753472339970

**Comment by jlbruno** [comment]
You can probably close this one based on the comment in your PR @Refactored

**Comment by seankearney** [comment]
You are correct. Thanks!.

This request was closed with PR #20
