### ISSUE TITLE
Set "EnableAncestorFallback" and "DefaultFieldFallback" field to shared

### ISSUE THREAD

**Issue by aquasonic** [HedgehogDevelopment/sitecore-field-fallback#7]
Hi,

today we figured out an issue with the fallback configuration. On each field we can enable the ancestor fallback and the default fieldback with the fields `EnableAncestorFallback` and `DefaultFieldFallback`, which are defined on the `/sitecore/templates/System/Templates/Template field`. These fields are not shared, which means that we need to create all the template fields in all languages to enable the fallback for each language.

Is there a reason that these fields are not shared? In my opinion these should be shared, because a fallback is either enabled or not. The cache which stores if the fallback is enabled for a field is also language independent, which results in unexpected behaviors (you need to first hit the item in the Content Editor, then it works).

If there is no reason, can you please make this field shared in a future release?

**Comment by hhog-tkamin** [comment]
Wiki has been updated with this information on the Ancestor and Default configuration sections.
