### ISSUE TITLE
Newly created item (in a bucket) doesn't show fallback values

### ISSUE THREAD

**Issue by seankearney** [HedgehogDevelopment/sitecore-field-fallback#9]
When an item is created inside a bucket, the fallback values aren't shown in a field. If the item is refreshed, the fallback values are seen. (Sometimes this is only demonstrated if the 'view buckets' option is checked).

Duplicated with Sitecore 7.1 (140130 & 140324)

**Comment by hhog-tkamin** [comment]
Unable to recreate in 7.2 140526 and 8 150812
